#      dMMMMMP dMP dMP dMMMMMP dMMMMb dMMMMMMP            
#     dMP     dMP dMP dMP     dMP dMP   dMP               
#    dMMMP   dMP dMP dMMMP   dMP dMP   dMP                
#   dMP      YMvAP" dMP     dMP dMP   dMP                 
#  dMMMMMP    VP"  dMMMMMP dMP dMP   dMP                  
#                                                         
#      dMP dMP .aMMMb  dMMMMb  dMP dMMMMMP .aMMMb  dMMMMb 
#     dMP dMP dMP"dMP dMP.dMP amr   .dMP" dMP"dMP dMP dMP 
#    dMMMMMP dMP dMP dMMMMK" dMP  .dMP"  dMP dMP dMP dMP  
#   dMP dMP dMP.aMP dMP"AMF dMP .dMP"   dMP.aMP dMP dMP   
#  dMP dMP  VMMMP" dMP dMP dMP dMMMMMP  VMMMP" dMP dMP    
#                                                         

# Accent and UI colors
accent = "#26bbd9"
active_border_color = "#3fc4de"
active_tab_background = "#26bbd9"

# Cursor colors
cursor = "#fadad1"

# Primary colors
foreground = "#fadad1"
background = "#1c1e26"

# Selection colors
selection_foreground = "#1c1e26"
selection_background = "#26bbd9"

# Normal colors (ANSI 0-7)
color0 = "#1c1e26"
color1 = "#e95678"
color2 = "#29d398"
color3 = "#fab795"
color4 = "#26bbd9"
color5 = "#ee64ac"
color6 = "#59e3e3"
color7 = "#fadad1"

# Bright colors (ANSI 8-15)
color8 = "#6c6f93"
color9 = "#ec6a88"
color10 = "#3fdaa4"
color11 = "#fbc3a7"
color12 = "#3fc4de"
color13 = "#f075b5"
color14 = "#6be4e6"
color15 = "#fadad1"
#  
#  _______/\\\\\_______/\\\\\\____________/\\\__                                                  
#   _____/\\\///\\\____\////\\\___________\/\\\__                                                 
#    ___/\\\/__\///\\\_____\/\\\___________\/\\\__                                                
#     __/\\\______\//\\\____\/\\\___________\/\\\__                                               
#      _\/\\\_______\/\\\____\/\\\______/\\\\\\\\\__                                              
#       _\//\\\______/\\\_____\/\\\_____/\\\////\\\__                                             
#        __\///\\\__/\\\_______\/\\\____\/\\\__\/\\\__                                            
#         ____\///\\\\\/______/\\\\\\\\\_\//\\\\\\\/\\_                                           
#          ______\/////_______\/////////___\///////\//__                                          
#  ______/\\\\\\\\\\\________________/\\\_______________________/\\\______________________        
#   _____\/////\\\///________________\/\\\______________________\/\\\______________________       
#    _________\/\\\___________________\/\\\______________________\/\\\______________________      
#     _________\/\\\_________/\\\\\____\/\\\____________/\\\\\____\/\\\____________/\\\\\____     
#      _________\/\\\_______/\\\///\\\__\/\\\\\\\\\____/\\\///\\\__\/\\\\\\\\\____/\\\///\\\__    
#       _________\/\\\______/\\\__\//\\\_\/\\\////\\\__/\\\__\//\\\_\/\\\////\\\__/\\\__\//\\\_   
#        __/\\\___\/\\\_____\//\\\__/\\\__\/\\\__\/\\\_\//\\\__/\\\__\/\\\__\/\\\_\//\\\__/\\\__  
#         _\//\\\\\\\\\_______\///\\\\\/___\/\\\\\\\\\___\///\\\\\/___\/\\\\\\\\\___\///\\\\\/___ 
#          __\/////////__________\/////_____\/////////______\/////_____\/////////______\/////_____
#  
